import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "./request/ReactQueryProvider";
import { HomePageProvider } from "./context/homePageContext";
import { ServicePageProvider } from "./context/servicePageContext";
import { AboutPageProvider } from "./context/aboutPageContext";
import { ContactPageProvider } from "./context/contactPageContext";
import { SeoPageProvider } from "./context/seoPageContext";
import { PPCPageProvider } from "./context/ppcPageContext";
import { PressPageProvider } from "./context/pressPageContext";
import { SocialsPageProvider } from "./context/socialPageContext";
import { WebDevelopmentPageProvider } from "./context/webDevelopmentPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <HomePageProvider>
            <ServicePageProvider>
              <AboutPageProvider>
                <ContactPageProvider>
                  <SeoPageProvider>
                    <PPCPageProvider>
                      <PressPageProvider>
                        <SocialsPageProvider>
                          <WebDevelopmentPageProvider>
                            {children}
                          </WebDevelopmentPageProvider>
                        </SocialsPageProvider>
                      </PressPageProvider>
                    </PPCPageProvider>
                  </SeoPageProvider>
                </ContactPageProvider>   
              </AboutPageProvider>
            </ServicePageProvider>
          </HomePageProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
